### ISSUE TITLE
Units advancing twice or more times when adding experience

### ISSUE THREAD

**Issue by Toranks** [sigurdfdragon/Gui_Debug_Tools#1]
Also, the experience is reset to 0. The number of times the unit level up depends on the experience added, but not respect the exact quantity. I don't know what is happen, really, but probably because are there advance events involved. There is more addons (Advanced Wesnot Wars), but all works well with any other way of experience gaining, only do problems with GUI Debug Tools way of adding experience.

https://user-images.githubusercontent.com/40789364/227605418-269555c3-1221-4674-8d59-41a091911685.mp4

**Comment by sigurdfdragon** [comment]
Which add-on and which version of Wesnoth are you using with GDT in the video?

**Comment by Toranks** [comment]
Version 1.17.14
Addons: Advanced Wesnoth Wars on LOTI campaign.

This happens without addons on units that have any AMLA that triggers an advance or post advance event, AFAIK. For example LOTI units, certain EoMa units, etc. What is in the video is an example (no addons directly involved on the advancement).

**Comment by sigurdfdragon** [comment]
Working on it, testing with LOTI units.
What are 2 or 3 EoMa units that I could test with?

**Comment by Toranks** [comment]
Here I show three examples. The first is normal behavior, with normal unit. The second is with Rasti, who although visually seems to advance normally, if you look closely she loses all his XP above 0, and internally she has advanced several times. Finally, Mejir, who levels up crazily until he loses all of his AMLA one by one.

[Youtube: EOMA + Gui Debug Tools](https://youtu.be/CGu44fuwr-c)

**Comment by sigurdfdragon** [comment]
I've identified the problem in the GDT code.

			unit_ops.level_type_advances_to_xp ( dbg_unit, temp_table.level, temp_table.type, temp_table.advances_to, temp_table.experience)
			unit_ops.advancements (dbg_unit, temp_table.advancements)

The first unit_op function handles the xp increase.
If an amla is added via an xp increase in the first unit_op, the the second unit_op drags the number of advancements back to what it was.

The bug you described is a case I missed taking into account when I added the advancements slider.

Next, I need to figure out the best way to handle it based on expected usage & design principles I have for GDT.
Could be merging the those two unit_ops functions, reordering them, preventing xp adjustments from leveling/advancing, some combination of those, and/or something else.
When I do, I'll make a fix and upload a new version.

For the time being, the workaround is avoid using the xp slider to cause advancements on units at max level, and use the advancements slider instead.

Thanks for the report, Toranks.

**Comment by sigurdfdragon** [comment]
New version uploaded to 1.16 add-on servers.
Thanks again, Toranks.

**Comment by Toranks** [comment]
Thank you!
Just a thing without importance with the new update: If the unit's max experience grows above 516,000 or so, the experience slider breaks, showing strange, negative values, and cannot be adjusted well.
Although it is an extremely rare use case , of course xD

**Comment by Toranks** [comment]
A question. How do I advance a unit that is not at its maximum level with GUI debug tools? Doing it with the advancements slider is ignored and returns to the previous state when pressing Ok

**Comment by sigurdfdragon** [comment]
Level slider to level it to max first
As it is now, advancements slider only gives advancements when unit is at max level, though it can clear advancements at anytime. (ie you make a unit max level add 3 advancements, then lower unit level. can clear advancements in that case, but can't add any.)

**Comment by sigurdfdragon** [comment]
Also I'll update my github notifications so I'll see stuff on my add-ons quicker than I have been.
Though a forum pm will still be the quickest way to reach me.

**Comment by sigurdfdragon** [comment]
my notifications have been updated.
issues/pr's on my github repos, posts to my add-on threads at the forums, and forum pms will all reach me about 3x weekly.
discord is still not a good way to contact me.
