### ISSUE TITLE
GUI Debug tools creates an infinite loop with a self advancing unit

### ISSUE THREAD

**Issue by Toranks** [sigurdfdragon/Gui_Debug_Tools#3]
A self-advancing unit is probably a bug, but GUI Debug Tools shouldn't hang Wesnoth because of it.

How to reproduce:
- Open this savegame and use Unit Debug with Vlad (the enemy leader)
- Wesnoth freezes

[LotI1-Bajó de las montañas Turno 1.1.gz](https://github.com/sigurdfdragon/Gui_Debug_Tools/files/11533744/LotI1-Bajo.de.las.montanas.Turno.1.1.gz)

This units has been fixed on LOTI and it doesn't advance itself anymore (fixed here https://github.com/Dugy/Legend_of_the_Invincibles/pull/479), but it would be nice to make GUI debug tools tolerant of this situation.

**Comment by CelticMinstrel** [comment]
While this is clearly a bug in GUI Debug Tools, I think there should also be a way to escape an infinite loop in Lua without having to kill the entire game. An interrupt key would be a good feature request, or else some way to automatically give minimal control to the UI while Lua code is executing.

**Comment by sigurdfdragon** [comment]
Will add some sort of check or count thing to handle this.

**Comment by sigurdfdragon** [comment]
fix committed, will be in next release. Thanks, @Toranks 
The original check I wrote for identifying min & max values for the level slider was bugged, and has been fixed.

**Comment by sigurdfdragon** [comment]
Fix has been uploaded in 0.10.4
